// REPORTS ROUTE
const express = require('express');
const router = express.Router();
const db = require('../config/db');
const { auth } = require('../middleware/auth');
const PDFDocument = require('pdfkit');

router.get('/pdf', auth, async (req, res) => {
  try {
    const month = req.query.month || new Date().getMonth() + 1;
    const year  = req.query.year  || new Date().getFullYear();
    const userId = req.user.id;

    const [[{ totalIncome }]] = await db.execute(
      `SELECT COALESCE(SUM(amount),0) as totalIncome FROM income WHERE user_id=? AND MONTH(date)=? AND YEAR(date)=?`,
      [userId, month, year]
    );
    const [[{ totalExpenses }]] = await db.execute(
      `SELECT COALESCE(SUM(amount),0) as totalExpenses FROM expenses WHERE user_id=? AND MONTH(date)=? AND YEAR(date)=?`,
      [userId, month, year]
    );
    const [expenses] = await db.execute(
      `SELECT * FROM expenses WHERE user_id=? AND MONTH(date)=? AND YEAR(date)=? ORDER BY date DESC`,
      [userId, month, year]
    );
    const [incomes] = await db.execute(
      `SELECT * FROM income WHERE user_id=? AND MONTH(date)=? AND YEAR(date)=? ORDER BY date DESC`,
      [userId, month, year]
    );
    const [[user]] = await db.execute('SELECT name, email FROM users WHERE id=?', [userId]);
    const monthNames = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

    const doc = new PDFDocument({ margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=finance-report-${year}-${month}.pdf`);
    doc.pipe(res);

    // Header
    doc.fontSize(24).fillColor('#1a56db').text('Finance Report', { align: 'center' });
    doc.fontSize(12).fillColor('#666').text(`${monthNames[month-1]} ${year} | ${user.name} (${user.email})`, { align: 'center' });
    doc.moveDown().moveTo(50, doc.y).lineTo(550, doc.y).stroke('#ccc').moveDown();

    // Summary
    doc.fontSize(16).fillColor('#333').text('Summary');
    doc.fontSize(12).fillColor('#22c55e').text(`Total Income:   ₹${parseFloat(totalIncome).toFixed(2)}`);
    doc.fillColor('#ef4444').text(`Total Expenses: ₹${parseFloat(totalExpenses).toFixed(2)}`);
    doc.fillColor('#3b82f6').text(`Net Balance:    ₹${(parseFloat(totalIncome) - parseFloat(totalExpenses)).toFixed(2)}`);
    doc.moveDown();

    // Expenses
    if (expenses.length > 0) {
      doc.fontSize(16).fillColor('#333').text('Expenses');
      expenses.forEach(e => {
        doc.fontSize(10).fillColor('#555').text(`${e.date} | ${e.category} | ${e.title} | ₹${e.amount}`);
      });
      doc.moveDown();
    }

    // Income
    if (incomes.length > 0) {
      doc.fontSize(16).fillColor('#333').text('Income');
      incomes.forEach(i => {
        doc.fontSize(10).fillColor('#555').text(`${i.date} | ${i.category} | ${i.title} | ₹${i.amount}`);
      });
    }

    doc.moveDown().fontSize(10).fillColor('#999').text('Generated by AI Finance Manager', { align: 'center' });
    doc.end();
  } catch (err) {
    res.status(500).json({ message: 'PDF generation failed', error: err.message });
  }
});

module.exports = router;